version: 0.9.3.{build}

branches:
  only:
    - master

assembly_info:
  patch: true
  file: AssemblyInfo.*
  assembly_version: "{version}"
  assembly_file_version: "{version}"
  assembly_informational_version: "{version}"

configuration: Release

build_script:
- cmd: >-
    set DEVENV="%VS140COMNTOOLS%\..\IDE\devenv"

    %DEVENV% /build "release|x86" csharp\windows\Facebook.Yoga.Desktop.sln

    %DEVENV% /build "release|x64" csharp\windows\Facebook.Yoga.Desktop.sln

    %DEVENV% /build "release|ARM" csharp\windows\Facebook.Yoga.Desktop.sln

after_test:
  - ps: .\nuget\pack.ps1

artifacts:
  - path: Windows\Facebook.Yoga\bin\Release\Facebook.Yoga.dll
    name: Facebook.Yoga.dll
  - path: '**\*.nupkg'

#uncomment to publish to NuGet
#deploy:
#  provider: NuGet
#  api_key:
#    secure: n/2gZwCGLcoLBr5nGu5akS0IFQ1YHciI6Wz0NGC+1mLTUtO08Uy+TWn7OtyLG9v3
#  artifact: /.*\.nupkg/
  
  
  